# docker-compose.yml
version: '3'
services:
  database:
    image: "postgres" # use latest official postgres version
    container_name: "green-api"
    env_file:
      - .env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
volumes:
  database-data: # named volumes can be managed easier using docker-compose
