version: '3'
services:
  web:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file: .env
  db:
    image: postgres:latest
    container_name: green-api
    ports:
      - "5432:5432"
    env_file: .env
    volumes:
      - db:/var/lib/postgresql/data
