# version: '3'
# services:
#   db:
#     image: postgres:latest
#     restart: always
#     container_name: teste
#     ports:
#       - "5432:5432"
#     environment:
#       POSTGRES_USER:
#       POSTGRES_PASSWORD:
#       POSTGRES_NAME: green-api
