'use strict';

module.exports = {
  up: async (queryInterface) => {
    await queryInterface.bulkInsert(
      'greens',
      [
        {
          project_id: 1,
          infos:
            'Auroras are the result of disturbances in the magnetosphere caused by solar wind. These disturbances are sometimes strong enough to alter the trajectories of charged particles in both solar wind and magnetospheric plasma. These particles, mainly electrons and protons, precipitate into the upper atmosphere (thermosphere/exosphere).',
          ph_water: 10.2,
          ph_soil: 10.2,
          ec: 11.223,
          temp_max: 2.334,
          temp_min: 2.334,
          moisture: 2.334,
          air_humidity: 2.334,
          phase: 'germination',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          project_id: 1,
          infos:
            'Auroras are the result of disturbances in the magnetosphere caused by solar wind. These disturbances are sometimes strong enough to alter the trajectories of charged particles in both solar wind and magnetospheric plasma. These particles, mainly electrons and protons, precipitate into the upper atmosphere (thermosphere/exosphere).',
          ph_water: 10.2,
          ph_soil: 10.2,
          ec: 11.223,
          temp_max: 2.334,
          temp_min: 2.334,
          moisture: 2.334,
          air_humidity: 2.334,
          phase: 'flowering',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          project_id: 1,
          infos:
            'Auroras are the result of disturbances in the magnetosphere caused by solar wind. These disturbances are sometimes strong enough to alter the trajectories of charged particles in both solar wind and magnetospheric plasma. These particles, mainly electrons and protons, precipitate into the upper atmosphere (thermosphere/exosphere).',
          ph_water: 10.2,
          ph_soil: 10.2,
          ec: 11.223,
          temp_max: 2.334,
          temp_min: 2.334,
          moisture: 2.334,
          air_humidity: 2.334,
          phase: 'flowering',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          project_id: 1,
          infos:
            'Auroras are the result of disturbances in the magnetosphere caused by solar wind. These disturbances are sometimes strong enough to alter the trajectories of charged particles in both solar wind and magnetospheric plasma. These particles, mainly electrons and protons, precipitate into the upper atmosphere (thermosphere/exosphere).',
          ph_water: 10.2,
          ph_soil: 10.2,
          ec: 11.223,
          temp_max: 2.334,
          temp_min: 2.334,
          moisture: 2.334,
          air_humidity: 2.334,
          phase: 'flowering',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          project_id: 1,
          infos:
            'Auroras are the result of disturbances in the magnetosphere caused by solar wind. These disturbances are sometimes strong enough to alter the trajectories of charged particles in both solar wind and magnetospheric plasma. These particles, mainly electrons and protons, precipitate into the upper atmosphere (thermosphere/exosphere).',
          ph_water: 10.2,
          ph_soil: 10.2,
          ec: 11.223,
          temp_max: 2.334,
          temp_min: 2.334,
          moisture: 2.334,
          air_humidity: 2.334,
          phase: 'flowering',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          project_id: 1,
          infos:
            'Auroras are the result of disturbances in the magnetosphere caused by solar wind. These disturbances are sometimes strong enough to alter the trajectories of charged particles in both solar wind and magnetospheric plasma. These particles, mainly electrons and protons, precipitate into the upper atmosphere (thermosphere/exosphere).',
          ph_water: 10.2,
          ph_soil: 10.2,
          ec: 11.223,
          temp_max: 2.334,
          temp_min: 2.334,
          moisture: 2.334,
          air_humidity: 2.334,
          phase: 'vegetation',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          project_id: 1,
          infos:
            'Auroras are the result of disturbances in the magnetosphere caused by solar wind. These disturbances are sometimes strong enough to alter the trajectories of charged particles in both solar wind and magnetospheric plasma. These particles, mainly electrons and protons, precipitate into the upper atmosphere (thermosphere/exosphere).',
          ph_water: 10.2,
          ph_soil: 10.2,
          ec: 11.223,
          temp_max: 2.334,
          temp_min: 2.334,
          moisture: 2.334,
          air_humidity: 2.334,
          phase: 'vegetation',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          project_id: 1,
          infos:
            'Auroras are the result of disturbances in the magnetosphere caused by solar wind. These disturbances are sometimes strong enough to alter the trajectories of charged particles in both solar wind and magnetospheric plasma. These particles, mainly electrons and protons, precipitate into the upper atmosphere (thermosphere/exosphere).',
          ph_water: 10.2,
          ph_soil: 10.2,
          ec: 11.223,
          temp_max: 2.334,
          temp_min: 2.334,
          moisture: 2.334,
          air_humidity: 2.334,
          phase: 'vegetation',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          project_id: 1,
          infos:
            'Auroras are the result of disturbances in the magnetosphere caused by solar wind. These disturbances are sometimes strong enough to alter the trajectories of charged particles in both solar wind and magnetospheric plasma. These particles, mainly electrons and protons, precipitate into the upper atmosphere (thermosphere/exosphere).',
          ph_water: 10.2,
          ph_soil: 10.2,
          ec: 11.223,
          temp_max: 2.334,
          temp_min: 2.334,
          moisture: 2.334,
          air_humidity: 2.334,
          phase: 'vegetation',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          project_id: 1,
          infos:
            'Auroras are the result of disturbances in the magnetosphere caused by solar wind. These disturbances are sometimes strong enough to alter the trajectories of charged particles in both solar wind and magnetospheric plasma. These particles, mainly electrons and protons, precipitate into the upper atmosphere (thermosphere/exosphere).',
          ph_water: 10.2,
          ph_soil: 10.2,
          ec: 11.223,
          temp_max: 2.334,
          temp_min: 2.334,
          moisture: 2.334,
          air_humidity: 2.334,
          phase: 'vegetation',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          project_id: 1,
          infos:
            'Auroras are the result of disturbances in the magnetosphere caused by solar wind. These disturbances are sometimes strong enough to alter the trajectories of charged particles in both solar wind and magnetospheric plasma. These particles, mainly electrons and protons, precipitate into the upper atmosphere (thermosphere/exosphere).',
          ph_water: 10.2,
          ph_soil: 10.2,
          ec: 11.223,
          temp_max: 2.334,
          temp_min: 2.334,
          moisture: 2.334,
          air_humidity: 2.334,
          phase: 'vegetation',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          project_id: 1,
          infos:
            'Auroras are the result of disturbances in the magnetosphere caused by solar wind. These disturbances are sometimes strong enough to alter the trajectories of charged particles in both solar wind and magnetospheric plasma. These particles, mainly electrons and protons, precipitate into the upper atmosphere (thermosphere/exosphere).',
          ph_water: 10.2,
          ph_soil: 10.2,
          ec: 11.223,
          temp_max: 2.334,
          temp_min: 2.334,
          moisture: 2.334,
          air_humidity: 2.334,
          phase: 'vegetation',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          project_id: 1,
          infos:
            'Auroras are the result of disturbances in the magnetosphere caused by solar wind. These disturbances are sometimes strong enough to alter the trajectories of charged particles in both solar wind and magnetospheric plasma. These particles, mainly electrons and protons, precipitate into the upper atmosphere (thermosphere/exosphere).',
          ph_water: 10.2,
          ph_soil: 10.2,
          ec: 11.223,
          temp_max: 2.334,
          temp_min: 2.334,
          moisture: 2.334,
          air_humidity: 2.334,
          phase: 'vegetation',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          project_id: 1,
          infos:
            'Auroras are the result of disturbances in the magnetosphere caused by solar wind. These disturbances are sometimes strong enough to alter the trajectories of charged particles in both solar wind and magnetospheric plasma. These particles, mainly electrons and protons, precipitate into the upper atmosphere (thermosphere/exosphere).',
          ph_water: 10.2,
          ph_soil: 10.2,
          ec: 11.223,
          temp_max: 2.334,
          temp_min: 2.334,
          moisture: 2.334,
          air_humidity: 2.334,
          phase: 'germination',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          project_id: 1,
          infos:
            'Auroras are the result of disturbances in the magnetosphere caused by solar wind. These disturbances are sometimes strong enough to alter the trajectories of charged particles in both solar wind and magnetospheric plasma. These particles, mainly electrons and protons, precipitate into the upper atmosphere (thermosphere/exosphere).',
          ph_water: 10.2,
          ph_soil: 10.2,
          ec: 11.223,
          temp_max: 2.334,
          temp_min: 2.334,
          moisture: 2.334,
          air_humidity: 2.334,
          phase: 'germination',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          project_id: 1,
          infos:
            'Auroras are the result of disturbances in the magnetosphere caused by solar wind. These disturbances are sometimes strong enough to alter the trajectories of charged particles in both solar wind and magnetospheric plasma. These particles, mainly electrons and protons, precipitate into the upper atmosphere (thermosphere/exosphere).',
          ph_water: 10.2,
          ph_soil: 10.2,
          ec: 11.223,
          temp_max: 2.334,
          temp_min: 2.334,
          moisture: 2.334,
          air_humidity: 2.334,
          phase: 'germination',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          project_id: 1,
          infos:
            'Auroras are the result of disturbances in the magnetosphere caused by solar wind. These disturbances are sometimes strong enough to alter the trajectories of charged particles in both solar wind and magnetospheric plasma. These particles, mainly electrons and protons, precipitate into the upper atmosphere (thermosphere/exosphere).',
          ph_water: 10.2,
          ph_soil: 10.2,
          ec: 11.223,
          temp_max: 2.334,
          temp_min: 2.334,
          moisture: 2.334,
          air_humidity: 2.334,
          phase: 'germination',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          project_id: 1,
          infos:
            'Auroras are the result of disturbances in the magnetosphere caused by solar wind. These disturbances are sometimes strong enough to alter the trajectories of charged particles in both solar wind and magnetospheric plasma. These particles, mainly electrons and protons, precipitate into the upper atmosphere (thermosphere/exosphere).',
          ph_water: 10.2,
          ph_soil: 10.2,
          ec: 11.223,
          temp_max: 2.334,
          temp_min: 2.334,
          moisture: 2.334,
          air_humidity: 2.334,
          phase: 'germination',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          project_id: 1,
          infos:
            'Auroras are the result of disturbances in the magnetosphere caused by solar wind. These disturbances are sometimes strong enough to alter the trajectories of charged particles in both solar wind and magnetospheric plasma. These particles, mainly electrons and protons, precipitate into the upper atmosphere (thermosphere/exosphere).',
          ph_water: 10.2,
          ph_soil: 10.2,
          ec: 11.223,
          temp_max: 2.334,
          temp_min: 2.334,
          moisture: 2.334,
          air_humidity: 2.334,
          phase: 'germination',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          project_id: 1,
          infos:
            'Auroras are the result of disturbances in the magnetosphere caused by solar wind. These disturbances are sometimes strong enough to alter the trajectories of charged particles in both solar wind and magnetospheric plasma. These particles, mainly electrons and protons, precipitate into the upper atmosphere (thermosphere/exosphere).',
          ph_water: 10.2,
          ph_soil: 10.2,
          ec: 11.223,
          temp_max: 2.334,
          temp_min: 2.334,
          moisture: 2.334,
          air_humidity: 2.334,
          phase: 'germination',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          project_id: 1,
          infos:
            'Auroras are the result of disturbances in the magnetosphere caused by solar wind. These disturbances are sometimes strong enough to alter the trajectories of charged particles in both solar wind and magnetospheric plasma. These particles, mainly electrons and protons, precipitate into the upper atmosphere (thermosphere/exosphere).',
          ph_water: 10.2,
          ph_soil: 10.2,
          ec: 11.223,
          temp_max: 2.334,
          temp_min: 2.334,
          moisture: 2.334,
          air_humidity: 2.334,
          phase: 'germination',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          project_id: 1,
          infos:
            'Auroras are the result of disturbances in the magnetosphere caused by solar wind. These disturbances are sometimes strong enough to alter the trajectories of charged particles in both solar wind and magnetospheric plasma. These particles, mainly electrons and protons, precipitate into the upper atmosphere (thermosphere/exosphere).',
          ph_water: 10.2,
          ph_soil: 10.2,
          ec: 11.223,
          temp_max: 2.334,
          temp_min: 2.334,
          moisture: 2.334,
          air_humidity: 2.334,
          phase: 'germination',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          project_id: 1,
          infos:
            'Auroras are the result of disturbances in the magnetosphere caused by solar wind. These disturbances are sometimes strong enough to alter the trajectories of charged particles in both solar wind and magnetospheric plasma. These particles, mainly electrons and protons, precipitate into the upper atmosphere (thermosphere/exosphere).',
          ph_water: 10.2,
          ph_soil: 10.2,
          ec: 11.223,
          temp_max: 2.334,
          temp_min: 2.334,
          moisture: 2.334,
          air_humidity: 2.334,
          phase: 'germination',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          project_id: 1,
          infos:
            'Auroras are the result of disturbances in the magnetosphere caused by solar wind. These disturbances are sometimes strong enough to alter the trajectories of charged particles in both solar wind and magnetospheric plasma. These particles, mainly electrons and protons, precipitate into the upper atmosphere (thermosphere/exosphere).',
          ph_water: 10.2,
          ph_soil: 10.2,
          ec: 11.223,
          temp_max: 2.334,
          temp_min: 2.334,
          moisture: 2.334,
          air_humidity: 2.334,
          phase: 'germination',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          project_id: 1,
          infos:
            'Auroras are the result of disturbances in the magnetosphere caused by solar wind. These disturbances are sometimes strong enough to alter the trajectories of charged particles in both solar wind and magnetospheric plasma. These particles, mainly electrons and protons, precipitate into the upper atmosphere (thermosphere/exosphere).',
          ph_water: 10.2,
          ph_soil: 10.2,
          ec: 11.223,
          temp_max: 2.334,
          temp_min: 2.334,
          moisture: 2.334,
          air_humidity: 2.334,
          phase: 'germination',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          project_id: 1,
          infos:
            'Auroras are the result of disturbances in the magnetosphere caused by solar wind. These disturbances are sometimes strong enough to alter the trajectories of charged particles in both solar wind and magnetospheric plasma. These particles, mainly electrons and protons, precipitate into the upper atmosphere (thermosphere/exosphere).',
          ph_water: 10.2,
          ph_soil: 10.2,
          ec: 11.223,
          temp_max: 2.334,
          temp_min: 2.334,
          moisture: 2.334,
          air_humidity: 2.334,
          phase: 'germination',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          project_id: 1,
          infos:
            'Auroras are the result of disturbances in the magnetosphere caused by solar wind. These disturbances are sometimes strong enough to alter the trajectories of charged particles in both solar wind and magnetospheric plasma. These particles, mainly electrons and protons, precipitate into the upper atmosphere (thermosphere/exosphere).',
          ph_water: 10.2,
          ph_soil: 10.2,
          ec: 11.223,
          temp_max: 2.334,
          temp_min: 2.334,
          moisture: 2.334,
          air_humidity: 2.334,
          phase: 'germination',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          project_id: 1,
          infos:
            'Auroras are the result of disturbances in the magnetosphere caused by solar wind. These disturbances are sometimes strong enough to alter the trajectories of charged particles in both solar wind and magnetospheric plasma. These particles, mainly electrons and protons, precipitate into the upper atmosphere (thermosphere/exosphere).',
          ph_water: 10.2,
          ph_soil: 10.2,
          ec: 11.223,
          temp_max: 2.334,
          temp_min: 2.334,
          moisture: 2.334,
          air_humidity: 2.334,
          phase: 'germination',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          project_id: 1,
          infos:
            'Auroras are the result of disturbances in the magnetosphere caused by solar wind. These disturbances are sometimes strong enough to alter the trajectories of charged particles in both solar wind and magnetospheric plasma. These particles, mainly electrons and protons, precipitate into the upper atmosphere (thermosphere/exosphere).',
          ph_water: 43.1,
          ph_soil: 30.4,
          ec: 15.263,
          temp_max: 2.334,
          temp_min: 2.334,
          moisture: 2.334,
          air_humidity: 2.334,
          phase: 'germination',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          project_id: 1,
          infos:
            'Auroras are the result of disturbances in the magnetosphere caused by solar wind. These disturbances are sometimes strong enough to alter the trajectories of charged particles in both solar wind and magnetospheric plasma. These particles, mainly electrons and protons, precipitate into the upper atmosphere (thermosphere/exosphere).',
          ph_water: 10.2,
          ph_soil: 10.2,
          ec: 11.223,
          temp_max: 2.334,
          temp_min: 2.334,
          moisture: 2.334,
          air_humidity: 2.334,
          phase: 'germination',
          created_at: new Date(),
          updated_at: new Date(),
        },
      ],
      {}
    );
  },

  down: async (queryInterface) => {
    await queryInterface.bulkDelete('greens', null, {});
  },
};
