'use strict';

module.exports = {
  up: async (queryInterface) => {
    await queryInterface.bulkInsert(
      'greens',
      [
        {
          project_id: 1,
          infos: 'about sadmadf aknw akdapd awdapm camp ww',
          ph_water: 10.2,
          ph_soil: 10.2,
          ec: 11.223,
          temp_max: 2.334,
          temp_min: 2.334,
          moisture: 2.334,
          air_humidity: 2.334,
          phase: 'germination',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          project_id: 1,
          infos: 'about sadmadf aknw akdapd awdapm camp ww',
          ph_water: 10.2,
          ph_soil: 10.2,
          ec: 11.223,
          temp_max: 2.334,
          temp_min: 2.334,
          moisture: 2.334,
          air_humidity: 2.334,
          phase: 'germination',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          project_id: 1,
          infos: 'about sadmadf aknw akdapd awdapm camp ww',
          ph_water: 10.2,
          ph_soil: 10.2,
          ec: 11.223,
          temp_max: 2.334,
          temp_min: 2.334,
          moisture: 2.334,
          air_humidity: 2.334,
          phase: 'germination',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          project_id: 1,
          infos: 'about sadmadf aknw akdapd awdapm camp ww',
          ph_water: 10.2,
          ph_soil: 10.2,
          ec: 11.223,
          temp_max: 2.334,
          temp_min: 2.334,
          moisture: 2.334,
          air_humidity: 2.334,
          phase: 'germination',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          project_id: 1,
          infos: 'about sadmadf aknw akdapd awdapm camp ww',
          ph_water: 10.2,
          ph_soil: 10.2,
          ec: 11.223,
          temp_max: 2.334,
          temp_min: 2.334,
          moisture: 2.334,
          air_humidity: 2.334,
          phase: 'germination',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          project_id: 1,
          infos: 'about sadmadf aknw akdapd awdapm camp ww',
          ph_water: 10.2,
          ph_soil: 10.2,
          ec: 11.223,
          temp_max: 2.334,
          temp_min: 2.334,
          moisture: 2.334,
          air_humidity: 2.334,
          phase: 'germination',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          project_id: 1,
          infos: 'about sadmadf aknw akdapd awdapm camp ww',
          ph_water: 10.2,
          ph_soil: 10.2,
          ec: 11.223,
          temp_max: 2.334,
          temp_min: 2.334,
          moisture: 2.334,
          air_humidity: 2.334,
          phase: 'germination',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          project_id: 1,
          infos: 'about sadmadf aknw akdapd awdapm camp ww',
          ph_water: 10.2,
          ph_soil: 10.2,
          ec: 11.223,
          temp_max: 2.334,
          temp_min: 2.334,
          moisture: 2.334,
          air_humidity: 2.334,
          phase: 'germination',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          project_id: 1,
          infos: 'about sadmadf aknw akdapd awdapm camp ww',
          ph_water: 10.2,
          ph_soil: 10.2,
          ec: 11.223,
          temp_max: 2.334,
          temp_min: 2.334,
          moisture: 2.334,
          air_humidity: 2.334,
          phase: 'germination',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          project_id: 1,
          infos: 'about sadmadf aknw akdapd awdapm camp ww',
          ph_water: 10.2,
          ph_soil: 10.2,
          ec: 11.223,
          temp_max: 2.334,
          temp_min: 2.334,
          moisture: 2.334,
          air_humidity: 2.334,
          phase: 'germination',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          project_id: 1,
          infos: 'about sadmadf aknw akdapd awdapm camp ww',
          ph_water: 10.2,
          ph_soil: 10.2,
          ec: 11.223,
          temp_max: 2.334,
          temp_min: 2.334,
          moisture: 2.334,
          air_humidity: 2.334,
          phase: 'germination',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          project_id: 1,
          infos: 'about sadmadf aknw akdapd awdapm camp ww',
          ph_water: 10.2,
          ph_soil: 10.2,
          ec: 11.223,
          temp_max: 2.334,
          temp_min: 2.334,
          moisture: 2.334,
          air_humidity: 2.334,
          phase: 'germination',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          project_id: 1,
          infos: 'about sadmadf aknw akdapd awdapm camp ww',
          ph_water: 10.2,
          ph_soil: 10.2,
          ec: 11.223,
          temp_max: 2.334,
          temp_min: 2.334,
          moisture: 2.334,
          air_humidity: 2.334,
          phase: 'germination',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          project_id: 1,
          infos: 'about sadmadf aknw akdapd awdapm camp ww',
          ph_water: 10.2,
          ph_soil: 10.2,
          ec: 11.223,
          temp_max: 2.334,
          temp_min: 2.334,
          moisture: 2.334,
          air_humidity: 2.334,
          phase: 'germination',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          project_id: 1,
          infos: 'about sadmadf aknw akdapd awdapm camp ww',
          ph_water: 10.2,
          ph_soil: 10.2,
          ec: 11.223,
          temp_max: 2.334,
          temp_min: 2.334,
          moisture: 2.334,
          air_humidity: 2.334,
          phase: 'germination',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          project_id: 1,
          infos: 'about sadmadf aknw akdapd awdapm camp ww',
          ph_water: 10.2,
          ph_soil: 10.2,
          ec: 11.223,
          temp_max: 2.334,
          temp_min: 2.334,
          moisture: 2.334,
          air_humidity: 2.334,
          phase: 'germination',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          project_id: 1,
          infos: 'about sadmadf aknw akdapd awdapm camp ww',
          ph_water: 10.2,
          ph_soil: 10.2,
          ec: 11.223,
          temp_max: 2.334,
          temp_min: 2.334,
          moisture: 2.334,
          air_humidity: 2.334,
          phase: 'germination',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          project_id: 1,
          infos: 'about sadmadf aknw akdapd awdapm camp ww',
          ph_water: 10.2,
          ph_soil: 10.2,
          ec: 11.223,
          temp_max: 2.334,
          temp_min: 2.334,
          moisture: 2.334,
          air_humidity: 2.334,
          phase: 'germination',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          project_id: 1,
          infos: 'about sadmadf aknw akdapd awdapm camp ww',
          ph_water: 10.2,
          ph_soil: 10.2,
          ec: 11.223,
          temp_max: 2.334,
          temp_min: 2.334,
          moisture: 2.334,
          air_humidity: 2.334,
          phase: 'germination',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          project_id: 1,
          infos: 'about sadmadf aknw akdapd awdapm camp ww',
          ph_water: 10.2,
          ph_soil: 10.2,
          ec: 11.223,
          temp_max: 2.334,
          temp_min: 2.334,
          moisture: 2.334,
          air_humidity: 2.334,
          phase: 'germination',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          project_id: 1,
          infos: 'about sadmadf aknw akdapd awdapm camp ww',
          ph_water: 10.2,
          ph_soil: 10.2,
          ec: 11.223,
          temp_max: 2.334,
          temp_min: 2.334,
          moisture: 2.334,
          air_humidity: 2.334,
          phase: 'germination',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          project_id: 1,
          infos: 'about sadmadf aknw akdapd awdapm camp ww',
          ph_water: 10.2,
          ph_soil: 10.2,
          ec: 11.223,
          temp_max: 2.334,
          temp_min: 2.334,
          moisture: 2.334,
          air_humidity: 2.334,
          phase: 'germination',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          project_id: 1,
          infos: 'about sadmadf aknw akdapd awdapm camp ww',
          ph_water: 10.2,
          ph_soil: 10.2,
          ec: 11.223,
          temp_max: 2.334,
          temp_min: 2.334,
          moisture: 2.334,
          air_humidity: 2.334,
          phase: 'germination',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          project_id: 1,
          infos: 'about sadmadf aknw akdapd awdapm camp ww',
          ph_water: 10.2,
          ph_soil: 10.2,
          ec: 11.223,
          temp_max: 2.334,
          temp_min: 2.334,
          moisture: 2.334,
          air_humidity: 2.334,
          phase: 'germination',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          project_id: 1,
          infos: 'about sadmadf aknw akdapd awdapm camp ww',
          ph_water: 10.2,
          ph_soil: 10.2,
          ec: 11.223,
          temp_max: 2.334,
          temp_min: 2.334,
          moisture: 2.334,
          air_humidity: 2.334,
          phase: 'germination',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          project_id: 1,
          infos: 'about sadmadf aknw akdapd awdapm camp ww',
          ph_water: 10.2,
          ph_soil: 10.2,
          ec: 11.223,
          temp_max: 2.334,
          temp_min: 2.334,
          moisture: 2.334,
          air_humidity: 2.334,
          phase: 'germination',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          project_id: 1,
          infos: 'about sadmadf aknw akdapd awdapm camp ww',
          ph_water: 10.2,
          ph_soil: 10.2,
          ec: 11.223,
          temp_max: 2.334,
          temp_min: 2.334,
          moisture: 2.334,
          air_humidity: 2.334,
          phase: 'germination',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          project_id: 1,
          infos: 'about sadmadf aknw akdapd awdapm camp ww',
          ph_water: 10.2,
          ph_soil: 10.2,
          ec: 11.223,
          temp_max: 2.334,
          temp_min: 2.334,
          moisture: 2.334,
          air_humidity: 2.334,
          phase: 'germination',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          project_id: 1,
          infos: 'about sadmadf aknw akdapd awdapm camp ww',
          ph_water: 10.2,
          ph_soil: 10.2,
          ec: 11.223,
          temp_max: 2.334,
          temp_min: 2.334,
          moisture: 2.334,
          air_humidity: 2.334,
          phase: 'germination',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          project_id: 1,
          infos: 'about sadmadf aknw akdapd awdapm camp ww',
          ph_water: 10.2,
          ph_soil: 10.2,
          ec: 11.223,
          temp_max: 2.334,
          temp_min: 2.334,
          moisture: 2.334,
          air_humidity: 2.334,
          phase: 'germination',
          created_at: new Date(),
          updated_at: new Date(),
        },
      ],
      {}
    );
  },

  down: async (queryInterface) => {
    await queryInterface.bulkDelete('greens', null, {});
  },
};
